# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: virtual_arm
  joint_model_group_pose: initial_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
    - Joint5
    - Joint6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
my_controller:
  type: effort_controllers/JointPositionController
  joints:
    - Joint1
    - Joint2
    - Joint3
    - Joint4
    - Joint5
  gains:
    Joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1