virtual_arm: 
  arm_joint_controller: 
    type: "position_controllers/JointTrajectoryController"
    joints: 
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6      

    constraints: 
      stopped_velocity_tolerance: 0

      
  gazebo_ros_control/pid_gains: 
    Joint1: {p: 670, i: 1.0, d: 0.1}
    Joint2: {p: 230.0, i: 1.0, d: 0.1}
    Joint3: {p: 567, i: 1.0, d: 0.15}
    Joint4: {p: 560, i: 1.0, d: 0.1}
    Joint5: {p: 120, i: 1.0, d: 0.1}
    Joint6: {p: 100.0, i: 1.0, d: 0.1}
    
     

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100


