controller_list:
  - name: fake_arm_controller
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5

initial:  # Define initial robot poses.
  - group: arm
    pose: initial_pose
  - group: bat
    pose: bat_hit_pose
